### ISSUE TITLE
How to activate ContinuousPolling

### ISSUE THREAD

**Issue by gfollic** [acken/FSWatcher#5]
Hi I use FSWatcher to watch NFS linux drive.
I had to create a Seter for the ContinuousPolling property in order to activate this setting.
A simple FSW can't work with NFS. ContinuousPolling helped me to resolve this issue. this is why I love your tool!:) it works great

I assume that It can be done automatically through a combinaison of property.
Could you tell me how ?

Thanks

Gilles

**Comment by acken** [comment]
Hi, glad to hear it is useful. It should be able to auto-detect that it needs to poll continuously. However if it does not you can trigger a check using the ForceRefresh method on the Watcher class when you want changes.
